version: '3.4'

services:
  tga.chatwarden:
    ports:
      - ${SERVICE_EXTERNAL_PORT}:${SERVICE_INTERNAL_PORT}
    image: ${DOCKER_REGISTRY}tgachatwarden
    build:
      context: .
      dockerfile: TGA.ChatWarden/Dockerfile
    environment:
      TOKEN: ${TOKEN}
      MONGO_DB_CNNSTR: "mongodb://${MONGO_DB_USER}:${MONGO_DB_PWD}@${MONGO_DB_HOST}:${MONGO_DB_INTERNAL_PORT}"

  mongo:
    container_name: MongoDB
    hostname: ${MONGO_DB_HOST}
    image: mongo
    restart: always
    ports:
      - ${MONGO_DB_EXTERNAL_PORT}:${MONGO_DB_INTERNAL_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PWD}